name: Validate

on:
  workflow_run:
    workflows: ["Lint"]
    types:
      - completed
  workflow_dispatch:

permissions: {}

jobs:
  hassfest: # https://developers.home-assistant.io/blog/2020/04/16/hassfest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs: # https://github.com/hacs/action
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    name: HACS validation
    runs-on: ubuntu-latest
    steps:
      - name: Run HACS validation
        uses: hacs/action@main
        with:
          category: integration
          # Remove this 'ignore' key when you have added brand images for your integration
          # https://developers.home-assistant.io/docs/creating_integration_file_structure#local-brand-images-for-custom-integrations
          ignore: brands
